name             'sprout-atom'
maintainer       'Fernando'
maintainer_email 'fernandoasfj@gmail.com'
license          'MIT'
description      'Cookbook for managing atom'
version          '0.0.1'
supports         'mac_os_x'
depends          'homebrew'
